### ISSUE TITLE
Clarification on Repository License for Commercial Use

### ISSUE THREAD

**Issue by startover205** [Cliff-F/C2PencilKit#2]
Hello @Cliff-F  , Great repo! 
Could you please clarify the license for this repository? We're wondering if we could use the tool in our commercial app. Thank you!

**Comment by Cliff-F** [comment]
Feel free to use it in commercial projects.

**Comment by startover205** [comment]
That's great to hear. We appreciate your generosity in allowing commercial use of your tool. ☺️
